/**
 * ZK Proof Generation — runs entirely in the browser via Barretenberg WASM.
 *
 * Flow:
 * 1. User provides their secret note (secret + nullifier)
 * 2. We fetch the current Merkle tree state from the contract
 * 3. We generate a ZK proof locally (nothing leaves the browser)
 * 4. The proof + public inputs are returned for on-chain submission
 */

// Type for the note a user saves after depositing
export interface DepositNote {
  secret: bigint;
  nullifier: bigint;
  commitment: string; // hex
  leafIndex: number;
  denomination: string;
  chainId: number;
  timestamp: number;
}

// Type for the proof output ready for on-chain submission
export interface WithdrawProof {
  proof: Uint8Array;
  root: string;
  nullifierHash: string;
  recipient: string;
  relayer: string;
  fee: bigint;
}

/**
 * Generate a random field element for use as secret or nullifier.
 * Uses crypto.getRandomValues for cryptographic randomness.
 */
export function generateRandomFieldElement(): bigint {
  const bytes = new Uint8Array(31); // 31 bytes to stay within field
  crypto.getRandomValues(bytes);
  let result = BigInt(0);
  for (const b of bytes) {
    result = (result << BigInt(8)) + BigInt(b);
  }
  return result;
}

/**
 * Create a new deposit note with random secret and nullifier.
 */
export function createDepositNote(
  denomination: string,
  chainId: number
): { secret: bigint; nullifier: bigint } {
  return {
    secret: generateRandomFieldElement(),
    nullifier: generateRandomFieldElement(),
  };
}

/**
 * Serialize a deposit note to a string the user can save.
 * Format: mixer-<chainId>-<denomination>-<secret>-<nullifier>
 */
export function serializeNote(note: DepositNote): string {
  return `mixer-${note.chainId}-${note.denomination}-${note.secret.toString(16)}-${note.nullifier.toString(16)}-${note.leafIndex}-${note.commitment}`;
}

/**
 * Deserialize a note string back into a DepositNote.
 */
export function deserializeNote(noteString: string): DepositNote {
  const parts = noteString.split("-");
  if (parts.length < 7 || parts[0] !== "mixer") {
    throw new Error("Invalid note format");
  }

  return {
    chainId: parseInt(parts[1]),
    denomination: parts[2],
    secret: BigInt("0x" + parts[3]),
    nullifier: BigInt("0x" + parts[4]),
    leafIndex: parseInt(parts[5]),
    commitment: parts[6],
    timestamp: Date.now(),
  };
}

/**
 * Generate a ZK withdrawal proof.
 *
 * This is the core privacy function — it runs Barretenberg WASM in the
 * browser to produce a proof that:
 * 1. You know the secret + nullifier behind a commitment in the tree
 * 2. You haven't withdrawn before (nullifier hash is fresh)
 * 3. The funds should go to the specified recipient
 *
 * NOTHING private leaves the browser. Only the proof + public inputs are returned.
 */
export async function generateWithdrawProof(
  note: DepositNote,
  merkleRoot: string,
  merklePath: string[],
  recipient: string,
  relayer: string = "0x0000000000000000000000000000000000000000",
  fee: bigint = BigInt(0)
): Promise<WithdrawProof> {
  // Dynamic imports — only load WASM when actually generating a proof
  const { Noir } = await import("@noir-lang/noir_js");
  const { BarretenbergBackend } = await import(
    "@noir-lang/backend_barretenberg"
  );

  // Load the compiled circuit artifact
  // This file is generated by `nargo compile` and placed in public/
  // Compiled Noir artifact lives at this static path. The filename
  // matches `[package] name` in circuit/Nargo.toml — keep them in
  // sync if you rename the Noir project.
  const response = await fetch("/circuit/cashinviz.json");
  const circuit = await response.json();

  // Initialize Barretenberg backend (downloads WASM ~15MB first time)
  const backend = new BarretenbergBackend(circuit, { threads: navigator.hardwareConcurrency });
  const noir = new Noir(circuit);

  // Pre-compute nullifier_hash in the browser. Noir requires every
  // public input to be passed in concretely; the circuit then
  // constrains `nullifier_hash == pedersen_hash([nullifier])`. The
  // hash MUST match what `circuit/src/main.nr::compute_nullifier_hash`
  // computes (currently Pedersen — when Noir 1.x makes Poseidon2
  // public we'll migrate both sides at once and update this call too).
  // Passing the wrong hash family (or a literal "0", as the very
  // first version did) means `noir.execute(inputs)` fails during
  // witness generation because the assertion inside the circuit no
  // longer holds — better to fail loud here than to ship a soundness
  // bug where the same secret is spendable twice.
  const nullifierHashHex = await pedersenHashOf([note.nullifier]);

  // Prepare inputs matching the Noir circuit's main() signature
  const inputs = {
    // Private inputs
    secret: note.secret.toString(),
    nullifier: note.nullifier.toString(),
    leaf_index: note.leafIndex.toString(),
    merkle_path: merklePath,

    // Public inputs
    root: merkleRoot,
    nullifier_hash: nullifierHashHex,
    recipient: recipient,
    relayer: relayer,
    fee: fee.toString(),
  };

  // Generate proof entirely in the browser
  const isDev = process.env.NODE_ENV !== "production";
  if (isDev) console.time("proof-generation");
  const { witness } = await noir.execute(inputs);
  const proof = await backend.generateProof(witness);
  if (isDev) console.timeEnd("proof-generation");

  return {
    proof: proof.proof,
    root: merkleRoot,
    nullifierHash: nullifierHashHex,
    recipient,
    relayer,
    fee,
  };
}

/**
 * Pedersen hash of one or more BN254 field elements, returned as a
 * 0x-prefixed 32-byte hex string. Must produce the SAME output as
 * Noir's `std::hash::pedersen_hash` (the function the circuit uses).
 *
 * `bb.js` exposes `pedersenHash` directly; we serialize the resulting
 * `Fr` as fixed 32-byte hex so it round-trips cleanly into the
 * circuit's public-inputs vector and into ABI-encoded calldata.
 *
 * Lazy import so the ~15MB Barretenberg WASM dep doesn't bloat pages
 * that never generate a proof.
 */
async function pedersenHashOf(values: bigint[]): Promise<string> {
  const { Barretenberg, Fr } = await import("@aztec/bb.js");
  const bb = await Barretenberg.new();
  const frs = values.map((v) => new Fr(v));
  const out = await bb.pedersenHash(frs);
  // bb.js hash output is a Fr; serialize as fixed 32-byte hex.
  const buf = out.toBuffer();
  return "0x" + Array.from(buf).map((b) => b.toString(16).padStart(2, "0")).join("");
}
